# Generated by Django 5.2.12 on 2026-04-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tcg_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique card ID from JustTCG API",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "tcg",
                    models.CharField(
                        choices=[
                            ("pokemon", "Pokémon"),
                            ("mtg", "Magic: The Gathering"),
                            ("yugioh", "Yu-Gi-Oh!"),
                            ("onepiece", "One Piece"),
                            ("lorcana", "Lorcana"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("set_name", models.CharField(max_length=255)),
                ("set_code", models.CharField(blank=True, max_length=50)),
                (
                    "number",
                    models.CharField(
                        blank=True, help_text="Card number within set", max_length=20
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("holo_rare", "Holo Rare"),
                            ("ultra_rare", "Ultra Rare"),
                            ("secret_rare", "Secret Rare"),
                            ("special", "Special"),
                        ],
                        max_length=20,
                    ),
                ),
                ("artist", models.CharField(blank=True, max_length=255)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                (
                    "image_url_hi",
                    models.URLField(
                        blank=True, help_text="High-res image", max_length=500
                    ),
                ),
                (
                    "market_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "mid_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "foil_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("price_updated_at", models.DateTimeField(blank=True, null=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["tcg", "set_name", "number"],
                "indexes": [
                    models.Index(
                        fields=["tcg", "set_name"], name="cards_card_tcg_ebd54d_idx"
                    ),
                    models.Index(fields=["name"], name="cards_card_name_a125cc_idx"),
                ],
            },
        ),
    ]
