# Generated by Django 5.2.12 on 2026-04-06 20:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("M", "Mint"),
                            ("NM", "Near Mint"),
                            ("LP", "Lightly Played"),
                            ("MP", "Moderately Played"),
                            ("HP", "Heavily Played"),
                            ("DMG", "Damaged"),
                        ],
                        default="NM",
                        max_length=3,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_foil", models.BooleanField(default=False)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="What the user paid (for portfolio P&L)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "is_hunted",
                    models.BooleanField(default=False, help_text="On user's Want list"),
                ),
                (
                    "for_sale",
                    models.BooleanField(
                        default=False, help_text="User is willing to sell/trade"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_items",
                        to="cards.card",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "card", "condition", "is_foil")},
            },
        ),
    ]
