# Generated by Django 5.2.13 on 2026-04-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitem",
            name="alert_drop_pct",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="% drop that triggers a drop alert. Blank = site default (15%).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="alert_surge_pct",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="% rise that triggers a surge alert. Blank = site default (15%).",
                null=True,
            ),
        ),
    ]
